from PySide2 import QtGui, QtWidgets, QtCore

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName('MainWindow')
        MainWindow.setWindowTitle('Random Group Creator')
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        MainWindow.setCentralWidget(self.centralwidget)
        self.studentbar = QtWidgets.QToolBar('studentbar', MainWindow)
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.studentbar)
        self.actionAdd_Student = QtWidgets.QAction('Add Student')
        self.actionRemove_Student = QtWidgets.QAction('Remove Student')
        self.actionEdit_Student = QtWidgets.QAction('Edit Student')
        self.studentbar.addAction(self.actionAdd_Student)
        self.studentbar.addAction(self.actionRemove_Student)
        self.studentbar.addAction(self.actionEdit_Student)
        self.main_layout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.main_layout.setObjectName('main_layout')
        self.buttons_layout = QtWidgets.QGridLayout()
        self.list_layout = QtWidgets.QGridLayout()
        self.main_layout.addLayout(self.buttons_layout)
        self.main_layout.addLayout(self.list_layout)
        self.font1 = QtGui.QFont()
        self.font1.setPointSize(20)
        self.font1.setWeight(75)
        self.font2 = QtGui.QFont()
        self.font2.setPointSize(20)
        self.font2.setWeight(50)
        self.num_groups_label = QtWidgets.QLabel('Number of Groups:', font=self.font1)
        self.period_label = QtWidgets.QLabel('Period:', font=self.font1)
        self.select_period = QtWidgets.QComboBox()
        self.periods = ['2nd', '3rd', '4th', '5th']
        self.select_period.insertItems(0, self.periods)
        self.select_period.setFont(self.font2)
        self.num_of_groups = QtWidgets.QComboBox()
        self.possible_num_groups = [f'{x}' for x in range(2,16)]
        self.num_of_groups.insertItems(0, self.possible_num_groups)
        self.num_of_groups.setFont(self.font2)
        self.randomize_button = QtWidgets.QPushButton('Randomize!', font=self.font1, autoDefault=True, autoRepeat=True, autoRepeatInterval=50)
        self.buttons_layout.setColumnMinimumWidth(2,60)
        self.buttons_layout.setColumnMinimumWidth(5,60)
        self.buttons_layout.addWidget(self.num_groups_label, 0, 0)
        self.buttons_layout.addWidget(self.num_of_groups, 0, 1)
        self.buttons_layout.addWidget(self.period_label, 0, 3, alignment=QtCore.Qt.AlignRight)
        self.buttons_layout.addWidget(self.select_period, 0, 4)
        self.buttons_layout.addWidget(self.randomize_button, 0, 6)
        self.centralwidget.setLayout(self.main_layout)
        self.main_layout.setSizeConstraint(self.main_layout.SetFixedSize)